//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ChatRoomPrx extends com.zeroc.Ice.ObjectPrx
{
    default String join(String username, ChatCallbackPrx callback)
    {
        return join(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String join(String username, ChatCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_joinAsync(username, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> joinAsync(String username, ChatCallbackPrx callback)
    {
        return _iceI_joinAsync(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> joinAsync(String username, ChatCallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_joinAsync(username, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_joinAsync(String iceP_username, ChatCallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "join", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeProxy(iceP_callback);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String listUsernames()
    {
        return listUsernames(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String listUsernames(java.util.Map<String, String> context)
    {
        return _iceI_listUsernamesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> listUsernamesAsync()
    {
        return _iceI_listUsernamesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> listUsernamesAsync(java.util.Map<String, String> context)
    {
        return _iceI_listUsernamesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_listUsernamesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listUsernames", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void sendMessageBC(String sender, String s)
    {
        sendMessageBC(sender, s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendMessageBC(String sender, String s, java.util.Map<String, String> context)
    {
        _iceI_sendMessageBCAsync(sender, s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageBCAsync(String sender, String s)
    {
        return _iceI_sendMessageBCAsync(sender, s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageBCAsync(String sender, String s, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageBCAsync(sender, s, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendMessageBCAsync(String iceP_sender, String iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessageBC", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_s);
                 }, null);
        return f;
    }

    default void sendMessage(String sender, String s, String receptor)
    {
        sendMessage(sender, s, receptor, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendMessage(String sender, String s, String receptor, java.util.Map<String, String> context)
    {
        _iceI_sendMessageAsync(sender, s, receptor, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String sender, String s, String receptor)
    {
        return _iceI_sendMessageAsync(sender, s, receptor, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String sender, String s, String receptor, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(sender, s, receptor, context, false);
    }

    /**
     * @hidden
     * @param iceP_sender -
     * @param iceP_s -
     * @param iceP_receptor -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendMessageAsync(String iceP_sender, String iceP_s, String iceP_receptor, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_sender);
                     ostr.writeString(iceP_s);
                     ostr.writeString(iceP_receptor);
                 }, null);
        return f;
    }

    default String leave(String username)
    {
        return leave(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String leave(String username, java.util.Map<String, String> context)
    {
        return _iceI_leaveAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> leaveAsync(String username)
    {
        return _iceI_leaveAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> leaveAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_leaveAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_leaveAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leave", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default Response executeCommand(String username, String command)
    {
        return executeCommand(username, command, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Response executeCommand(String username, String command, java.util.Map<String, String> context)
    {
        return _iceI_executeCommandAsync(username, command, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Response> executeCommandAsync(String username, String command)
    {
        return _iceI_executeCommandAsync(username, command, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Response> executeCommandAsync(String username, String command, java.util.Map<String, String> context)
    {
        return _iceI_executeCommandAsync(username, command, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_command -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Response> _iceI_executeCommandAsync(String iceP_username, String iceP_command, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Response> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "executeCommand", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeString(iceP_command);
                 }, istr -> {
                     final com.zeroc.IceInternal.Holder<Response> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, Response.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatRoomPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatRoomPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatRoomPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatRoomPrx.class, _ChatRoomPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatRoomPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatRoomPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatRoomPrx ice_adapterId(String newAdapterId)
    {
        return (ChatRoomPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatRoomPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatRoomPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatRoomPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatRoomPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatRoomPrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatRoomPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatRoomPrx ice_connectionCached(boolean newCache)
    {
        return (ChatRoomPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatRoomPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatRoomPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatRoomPrx ice_secure(boolean b)
    {
        return (ChatRoomPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatRoomPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatRoomPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatRoomPrx ice_preferSecure(boolean b)
    {
        return (ChatRoomPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatRoomPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatRoomPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatRoomPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatRoomPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatRoomPrx ice_collocationOptimized(boolean b)
    {
        return (ChatRoomPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatRoomPrx ice_twoway()
    {
        return (ChatRoomPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatRoomPrx ice_oneway()
    {
        return (ChatRoomPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatRoomPrx ice_batchOneway()
    {
        return (ChatRoomPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatRoomPrx ice_datagram()
    {
        return (ChatRoomPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatRoomPrx ice_batchDatagram()
    {
        return (ChatRoomPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatRoomPrx ice_compress(boolean co)
    {
        return (ChatRoomPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatRoomPrx ice_timeout(int t)
    {
        return (ChatRoomPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatRoomPrx ice_connectionId(String connectionId)
    {
        return (ChatRoomPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatRoomPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatRoomPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::ChatRoom";
    }
}
